"""Paths to bundled image assets, plus helpers to load them as Qt objects.

Assets live in ``gui/assets`` so they resolve relative to this module
regardless of the working directory. Icons are generated by
``tools/generate_icons.py``; if they are absent we fall back to the raw logo PNG,
so the app still has a window icon before the generator has been run.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from PySide6.QtGui import QIcon, QPixmap

_ASSETS = Path(__file__).resolve().parent / "assets"

LOGO_PATH = _ASSETS / "orchestrator.png"
_ICON_DIR = _ASSETS / "icons"
# Sizes emitted by tools/generate_icons.py; QIcon picks the best for each use.
_ICON_SIZES = (16, 32, 48, 64, 128, 256, 512)


def logo_pixmap() -> QPixmap:
    """The full logo as a pixmap (empty if the asset is missing)."""
    return QPixmap(str(LOGO_PATH))


@lru_cache(maxsize=1)
def app_icon() -> QIcon:
    """The application icon, built from every generated square PNG size, or the
    raw logo as a fallback when the icon set has not been generated yet."""
    icon = QIcon()
    any_size = False
    for size in _ICON_SIZES:
        path = _ICON_DIR / f"orchestrator-{size}.png"
        if path.is_file():
            icon.addFile(str(path))
            any_size = True
    if not any_size and LOGO_PATH.is_file():
        icon.addFile(str(LOGO_PATH))
    return icon
